# Generated by Django 5.0.1 on 2024-02-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='u_comment',
        ),
    ]
