# Generated by Django 5.0.1 on 2024-02-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_rename_comment_comments_u_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='blog_com',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.blog_post'),
        ),
    ]
